services:
  web:
    image: ghcr.io/serialcoder-io/quotesflow/quotesflow:latest
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:${POSTGRES_TAG}
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - db_data:/var/lib/postgresql/data
    ports: 
      - 5432:5432

volumes:
  db_data:
