# Generated by Django 5.2.5 on 2025-09-02 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='owner',
        ),
        migrations.AddField(
            model_name='organization',
            name='first_name',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='First name'),
        ),
        migrations.AddField(
            model_name='organization',
            name='is_org',
            field=models.BooleanField(default=True, verbose_name='is organization'),
        ),
        migrations.AddField(
            model_name='organization',
            name='last_name',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='legal_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='legal ID value'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='legal_id_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='legal ID name'),
        ),
    ]
