# Generated by Django 5.2.5 on 2025-09-06 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='has_already_been_org_owner',
            field=models.BooleanField(default=False),
        ),
    ]
