# Generated by Django 5.2.5 on 2025-09-29 20:20

import django.db.models.deletion
import phonenumber_field.modelfields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_company', models.BooleanField(default=False, verbose_name='Is a company')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Customer name')),
                ('first_name', models.CharField(blank=True, max_length=60, null=True, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, max_length=60, null=True, verbose_name='Last name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('contact', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Phone number')),
                ('address', models.CharField(blank=True, max_length=250, null=True, verbose_name='Adresse')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'db_table': 'customer',
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='has_already_been_org_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='contact',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Phone number'),
        ),
        migrations.AddField(
            model_name='organization',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Organization email'),
        ),
        migrations.AddField(
            model_name='organization',
            name='initials',
            field=models.CharField(blank=True, help_text='E.g., "Org Name Ltd". If left empty, default initials (ON-LTD) will be generated. Used for invoices and quotes.', max_length=12, null=True, verbose_name='Organization initials'),
        ),
        migrations.AddField(
            model_name='organization',
            name='subscription_end',
            field=models.DateField(blank=True, null=True, verbose_name='subscription end date'),
        ),
        migrations.AddField(
            model_name='organization',
            name='trial_end',
            field=models.DateField(blank=True, null=True, verbose_name='trial end date'),
        ),
        migrations.AddField(
            model_name='organization',
            name='trial_start',
            field=models.DateField(blank=True, null=True, verbose_name='trial start date'),
        ),
        migrations.AddField(
            model_name='organizationuser',
            name='is_active_by_owner',
            field=models.BooleanField(default=True, verbose_name='active according to owner decision'),
        ),
        migrations.AddField(
            model_name='organizationuser',
            name='is_active_by_plan',
            field=models.BooleanField(default=True, verbose_name='active according to subscription plan'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='value_type',
            field=models.CharField(choices=[('bool', 'Bool'), ('int', 'Int')], default='bool', help_text='the type of the value: form exp for feature send invoice to client by email, the type of the the value will be true or false', max_length=8, verbose_name='value type'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='legal_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='legal ID number'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='legal_id_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Type of legal ID'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='organization name'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='slug',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='organizationuser',
            unique_together={('user', 'organization')},
        ),
        migrations.AddIndex(
            model_name='organizationuser',
            index=models.Index(fields=['user', 'organization'], name='organizatio_user_id_3d086c_idx'),
        ),
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.UniqueConstraint(condition=models.Q(('is_org', True)), fields=('name',), name='unique_org_name'),
        ),
        migrations.AddField(
            model_name='customer',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='accounts.organization', verbose_name='Organisation'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['organization'], name='customer_organiz_9356b1_idx'),
        ),
    ]
