# Generated by Django 5.2.5 on 2025-10-06 12:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customer_customuser_has_already_been_org_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='users',
        ),
        migrations.AddField(
            model_name='organization',
            name='members',
            field=models.ManyToManyField(through='accounts.OrganizationUser', to=settings.AUTH_USER_MODEL, verbose_name='Members'),
        ),
    ]
