# Generated by Django 5.2.5 on 2025-09-06 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_has_already_been_org_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='trial_end',
            field=models.DateField(blank=True, null=True, verbose_name='trial end date'),
        ),
        migrations.AddField(
            model_name='organization',
            name='trial_start',
            field=models.DateField(blank=True, null=True, verbose_name='trial start date'),
        ),
    ]
