# Generated by Django 5.2.5 on 2025-10-23 12:07

import django_quill.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_organization_users_organization_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='description',
            field=django_quill.fields.QuillField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='organization',
            name='industry',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Industry'),
        ),
    ]
