# Generated by Django 5.2.5 on 2025-09-06 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_organization_trial_end_organization_trial_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='subscription_end',
            field=models.DateField(blank=True, null=True, verbose_name='subscription end date'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='legal_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='legal ID number'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='legal_id_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Type of legal ID'),
        ),
    ]
