# Generated by Django 5.2.5 on 2025-10-26 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_organization_description_organization_industry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='industry',
        ),
        migrations.AddField(
            model_name='organization',
            name='industry_choice',
            field=models.CharField(blank=True, choices=[('technology', 'Technology / IT'), ('finance', 'Finance / Banking / Insurance'), ('healthcare', 'Healthcare / Medical'), ('education', 'Education / Training'), ('retail', 'Retail / E-commerce'), ('manufacturing', 'Manufacturing / Industrial'), ('construction', 'Construction / Real Estate'), ('transportation', 'Transportation / Logistics'), ('hospitality', 'Hospitality / Tourism'), ('food', 'Food & Beverage'), ('media', 'Media / Entertainment / Publishing'), ('marketing', 'Marketing / Advertising / Communication'), ('legal', 'Legal / Consulting'), ('energy', 'Energy / Utilities / Environment'), ('government', 'Government / Public Sector'), ('nonprofit', 'Non-profit / NGO'), ('agriculture', 'Agriculture / Farming'), ('telecom', 'Telecommunications'), ('arts', 'Arts / Culture / Design'), ('sport', 'Sport / Fitness / Leisure'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='industry_custom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
