# Generated by Django 5.2.5 on 2025-09-08 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_organization_name_organization_unique_org_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_active_by_owner',
            field=models.BooleanField(default=True, verbose_name='active according to owner decision'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_active_by_plan',
            field=models.BooleanField(default=True, verbose_name='active according to subscription plan'),
        ),
    ]
