# Generated by Django 5.2.5 on 2025-09-08 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_is_active_by_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_active_by_owner',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_active_by_plan',
        ),
        migrations.AddField(
            model_name='organizationuser',
            name='is_active_by_owner',
            field=models.BooleanField(default=True, verbose_name='active according to owner decision'),
        ),
        migrations.AddField(
            model_name='organizationuser',
            name='is_active_by_plan',
            field=models.BooleanField(default=True, verbose_name='active according to subscription plan'),
        ),
    ]
