# Generated by Django 5.2.5 on 2025-09-08 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_customuser_is_active_by_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='slug',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
