# Generated by Django 5.2.5 on 2025-09-09 11:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_organization_contact_organization_email_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='initials',
            field=models.CharField(blank=True, help_text='E.g., "Org Name Ltd". If left empty, default initials (ON-LTD) will be generated. Used for invoices and quotes.', max_length=12, null=True, verbose_name='Organization initials'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='organizationuser',
            unique_together={('user', 'organization')},
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['organization'], name='customer_organiz_9356b1_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationuser',
            index=models.Index(fields=['user', 'organization'], name='organizatio_user_id_3d086c_idx'),
        ),
    ]
