# Generated by Django 5.2.5 on 2025-09-09 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_organization_initials_alter_customer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='value_type',
            field=models.CharField(choices=[('bool', 'Bool'), ('int', 'Int')], default='bool', help_text='the type of the value: form exp for feature send invoice to client by email, the type of the the value will be true or false', max_length=8, verbose_name='value type'),
        ),
    ]
